spring:
   datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      primary: content #设置默认的数据源或者数据源组,默认值即为master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      druid:
        initial-size: 3
        max-active: 5
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          #login-username: admin
          #login-password: admin
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
      datasource:
        content:
          url: jdbc:mysql://101.42.238.233:3306/xcplus_content?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "Hm#2024@MySQL"
          driver-class-name: com.mysql.cj.jdbc.Driver
        media:
          url: jdbc:mysql://101.42.238.233:3306/xcplus_media?serverTimezone=UTC&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "Hm#2024@MySQL"
          driver-class-name: com.mysql.cj.jdbc.Driver
# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: YOUR_ACCESS_KEY_ID_HERE
    accessKeySecret: YOUR_ACCESS_KEY_SECRET_HERE
    bucketName: YOUR_BUCKET_NAME_HERE
